### ISSUE TITLE
Using the -t flag with the -s flag still outputs the file path.

### ISSUE THREAD

**Issue by Druanae** [Sweets/nougat#1]
Tested with `nougat -st`, `nougat -stc`, `nougat -stf` and `nougat -stfc`
It works fine if you combine with -s with any non -t flag.
![image](https://user-images.githubusercontent.com/22475536/30063415-8e76f994-9246-11e7-8ef7-f3690a745582.png)

**Comment by Sweets** [comment]
Oversight on my part. Fixed.
