### ISSUE TITLE
Referencing Commands

### ISSUE THREAD

**Issue by Sweets** [Sweets/nougat#15]
After a recent Pull Request, the backends no longer wrap commands with the `command` built-in.

Should this be changed back, or be prefixed with the bash-specific command escaping to prevent aliases from being referenced, as opposed to the binaries themselves?

Or rather, should we embrace aliases?

If the former, should we include a flag that allows users to pass their own flags to the commands?

**Comment by aidanharris** [comment]
Aliases won't run in a script so you don't need to worry about that. I think this is fine as is, `command` shouldn't be needed.
