### ISSUE TITLE
maim options

### ISSUE THREAD

**Issue by Brottweiler** [Sweets/nougat#17]
Is there a way to add options for maim, and if there isn't, can this be added to the config, or with the use of a option flag?

In imgur-screenshot's config there is this

```cfg
screenshot_select_command="maim -s -m 10 %img -b 3 -c 0.3,0.4,0.6,0.4 -u"
screenshot_window_command="maim -m 10 %img -b 3 -c 0.3,0.4,0.6,0.4 -u"
screenshot_full_command="maim -m 10 %img -b 3 -c 0.3,0.4,0.6,0.4 -u"
```

This way I can customize my maim selection box, but it doesn't seem possible with nougat.

**Comment by Sweets** [comment]
There isn't currently, but this was previously a planned feature before being scrapped.

I can see the application, so I'll add it once I get home, unless someone else beats me to it.
