### ISSUE TITLE
libnotify support

### ISSUE THREAD

**Issue by Brottweiler** [Sweets/nougat#19]
Use libnotify to send out notifications on successful screenshot captures and failures to take screenshot.

**Comment by Sweets** [comment]
My take on this is that there's no really point to it when you can just append `&& notify-send` to a command.

@aidanharris

**Comment by Brottweiler** [comment]
You can append notify-send, but that still gets sent even if you cancel nougat with escape.

**Comment by Sweets** [comment]
So ideally we should have the exit code set to what the screenshot backend returns, if applicable.

If you could test the backend that you're using with `command && notify-send 'test'` then hit escape and tell me if it sent the notification, that'd be great. No big deal if you can't, I'll test it later today in that case.

If you use maim or scrot, then the command should be easy enough (`maim` or `scrot`). ImageMagick can be tested with `import -window root`.

**Comment by Brottweiler** [comment]
Running `maim -s > test.png && notify-send "test"` and hitting ESC doesn't send a notification.

**Comment by Sweets** [comment]
Just what I needed, thank you.

Now it's just down to whether nougat should simply return the same exit code, or if there should be a post-command variable.

Post-command variable clutters the configuration (more), and would make the code slightly more complex. The same exit code would mean that a user could execute any command if nougat succeeds in taking a screenshot, but means users would have to constantly type the same thing over and over again (in the case of notifications).

Could do both, too. Which I'll likely end up doing.

**Comment by Sweets** [comment]
Should be good now, let me know.

**Comment by Brottweiler** [comment]
Yep! Now I can do `nougat && notify-send "Success"` and have it send notification when i make a screenshot, and no notification when I cancel with <kbd>ESC</kbd>!

Thanks!
